const VOCABULARY = [
  // From Kira's lessons - Politics & General
  { id: 1, german: "die Regierung", english: "government", article: "die", category: "Politics" },
  { id: 2, german: "die Demokratie", english: "democracy", article: "die", category: "Politics" },
  { id: 3, german: "das Gesetz", english: "law", article: "das", category: "Politics" },
  { id: 4, german: "die Entscheidung", english: "decision", article: "die", category: "Politics" },
  { id: 5, german: "die Verantwortung", english: "responsibility", article: "die", category: "Politics" },
  { id: 6, german: "die Wahl", english: "election", article: "die", category: "Politics" },
  { id: 7, german: "die Mehrheit", english: "majority", article: "die", category: "Politics" },
  { id: 8, german: "die Opposition", english: "opposition", article: "die", category: "Politics" },
  { id: 9, german: "die Debatte", english: "debate", article: "die", category: "Politics" },
  { id: 10, german: "der Kompromiss", english: "compromise", article: "der", category: "Politics" },
 
  // From Kira's lessons - Daily Life
  { id: 11, german: "das Medium", english: "medium / means", article: "das", category: "Daily Life" },
  { id: 12, german: "die Mathematik", english: "mathematics", article: "die", category: "Daily Life" },
  { id: 13, german: "die Aktien", english: "stocks / shares", article: "die", category: "Finance", plural: true },
  { id: 14, german: "die Firma", english: "company", article: "die", category: "Work" },
  { id: 15, german: "der Ingenieur", english: "engineer", article: "der", category: "Work" },
  { id: 16, german: "peinlich", english: "embarrassing", article: null, category: "Adjectives" },
  { id: 17, german: "verständlich", english: "understandable", article: null, category: "Adjectives" },
  { id: 18, german: "verwirrend", english: "confusing", article: null, category: "Adjectives" },
  { id: 19, german: "darum", english: "that's why / therefore", article: null, category: "Connectors" },
  { id: 20, german: "das Ticket", english: "ticket", article: "das", category: "Travel" },
 
  // Football / Budapest
  { id: 21, german: "der Sieg", english: "victory", article: "der", category: "Football" },
  { id: 22, german: "unentschieden", english: "draw", article: null, category: "Football" },
  { id: 23, german: "der Außenseiter", english: "underdog", article: "der", category: "Football" },
  { id: 24, german: "das Elfmeterschießen", english: "penalty shootout", article: "das", category: "Football" },
  { id: 25, german: "die Niederlage", english: "defeat", article: "die", category: "Football" },
  { id: 26, german: "die Atmosphäre", english: "atmosphere", article: "die", category: "Football" },
  { id: 27, german: "die Gänsehaut", english: "goosebumps", article: "die", category: "Feelings" },
  { id: 28, german: "leidenschaftlich", english: "passionate", article: null, category: "Adjectives" },
  { id: 29, german: "einzigartig", english: "unique", article: null, category: "Adjectives" },
  { id: 30, german: "unvergesslich", english: "unforgettable", article: null, category: "Adjectives" },
  { id: 31, german: "überzeugt", english: "convinced", article: null, category: "Adjectives" },
 
  // Travel
  { id: 32, german: "der Zwischenstopp", english: "layover", article: "der", category: "Travel" },
  { id: 33, german: "die Rückreise", english: "return journey", article: "die", category: "Travel" },
  { id: 34, german: "das Terminal", english: "terminal", article: "das", category: "Travel" },
  { id: 35, german: "das Geschäft", english: "shop", article: "das", category: "Daily Life" },
  { id: 36, german: "angekommen", english: "arrived", article: null, category: "Travel" },
 
  // People / Social
  { id: 37, german: "der Kellner", english: "waiter", article: "der", category: "People" },
  { id: 38, german: "der Mitarbeiter", english: "worker / employee", article: "der", category: "Work" },
  { id: 39, german: "die Bekannten", english: "acquaintances", article: "die", category: "People", plural: true },
 
  // TV / Film
  { id: 40, german: "der Untertitel", english: "subtitle", article: "der", category: "Film & TV" },
  { id: 41, german: "die Episode / die Folge", english: "episode", article: "die", category: "Film & TV" },
  { id: 42, german: "die Serie", english: "TV show / series", article: "die", category: "Film & TV" },
  { id: 43, german: "die Staffel", english: "season (of a show)", article: "die", category: "Film & TV" },
  { id: 44, german: "die Leiche", english: "body (dead)", article: "die", category: "Film & TV" },
  { id: 45, german: "der Mord", english: "murder", article: "der", category: "Film & TV" },
  { id: 46, german: "die Lawine", english: "avalanche", article: "die", category: "Nature" },
  { id: 47, german: "die Brücke", english: "bridge", article: "die", category: "Places" },
 
  // Language learning
  { id: 48, german: "das Hörverständnis", english: "listening comprehension", article: "das", category: "Language" },
  { id: 49, german: "die Dauer", english: "duration", article: "die", category: "Language" },
  { id: 50, german: "die Geschwindigkeit", english: "speed", article: "die", category: "Language" },
  { id: 51, german: "das Muster", english: "pattern", article: "das", category: "Language" },
  { id: 52, german: "das Abo", english: "subscription", article: "das", category: "Daily Life" },
  { id: 53, german: "selten", english: "rarely", article: null, category: "Adverbs" },
  { id: 54, german: "einige", english: "quite a few / some", article: null, category: "Adverbs" },
  { id: 55, german: "außer", english: "except", article: null, category: "Connectors" },
  { id: 56, german: "unglaublich", english: "incredible / unbelievable", article: null, category: "Adjectives" },
  { id: 57, german: "der Satz", english: "sentence / phrase", article: "der", category: "Language" },
 
  // Feelings
  { id: 58, german: "aufgeregt", english: "excited (positive)", article: null, category: "Feelings" },
  { id: 59, german: "enttäuscht", english: "disappointed", article: null, category: "Feelings" },
  { id: 60, german: "zufrieden", english: "satisfied", article: null, category: "Feelings" },
  { id: 61, german: "einsam", english: "lonely", article: null, category: "Feelings" },
  { id: 62, german: "beschäftigt", english: "busy", article: null, category: "Adjectives" },
  { id: 63, german: "herzzerreißend", english: "heartbreaking", article: null, category: "Feelings" },
 
  // Reflexive verbs
  { id: 64, german: "sich erinnern an", english: "to remember (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 65, german: "sich freuen auf", english: "to look forward to (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 66, german: "sich freuen über", english: "to be happy about (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 67, german: "sich beschweren über", english: "to complain about (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 68, german: "sich kümmern um", english: "to take care of (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 69, german: "sich gewöhnen an", english: "to get used to (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 70, german: "sich anpassen an", english: "to adapt to (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 71, german: "sich interessieren für", english: "to be interested in (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 72, german: "sich entscheiden für", english: "to decide on (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 73, german: "sich vorbereiten auf", english: "to prepare for (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 74, german: "sich konzentrieren auf", english: "to focus on (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 75, german: "sich beschäftigen mit", english: "to deal with (+ Dat)", article: null, category: "Reflexive Verbs" },
  { id: 76, german: "sich einigen auf", english: "to agree on (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 77, german: "sich bemühen um", english: "to make an effort (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 78, german: "sich verändern", english: "to change (oneself)", article: null, category: "Reflexive Verbs" },
  { id: 79, german: "sich entwickeln", english: "to develop", article: null, category: "Reflexive Verbs" },
  { id: 80, german: "sich fühlen", english: "to feel", article: null, category: "Reflexive Verbs" },
  { id: 81, german: "sich entspannen", english: "to relax", article: null, category: "Reflexive Verbs" },
  { id: 82, german: "sich verbessern", english: "to improve oneself", article: null, category: "Reflexive Verbs" },
 
  // Präteritum forms
  { id: 83, german: "war (sein)", english: "was (to be) - Präteritum", article: null, category: "Präteritum" },
  { id: 84, german: "hatte (haben)", english: "had (to have) - Präteritum", article: null, category: "Präteritum" },
  { id: 85, german: "ging (gehen)", english: "went (to go) - Präteritum", article: null, category: "Präteritum" },
  { id: 86, german: "kam (kommen)", english: "came (to come) - Präteritum", article: null, category: "Präteritum" },
  { id: 87, german: "flog (fliegen)", english: "flew (to fly) - Präteritum", article: null, category: "Präteritum" },
  { id: 88, german: "sah (sehen)", english: "saw (to see) - Präteritum", article: null, category: "Präteritum" },
  { id: 89, german: "trank (trinken)", english: "drank (to drink) - Präteritum", article: null, category: "Präteritum" },
  { id: 90, german: "sang (singen)", english: "sang (to sing) - Präteritum", article: null, category: "Präteritum" },
  { id: 91, german: "gewann (gewinnen)", english: "won (to win) - Präteritum", article: null, category: "Präteritum" },
  { id: 92, german: "verlor (verlieren)", english: "lost (to lose) - Präteritum", article: null, category: "Präteritum" },
  { id: 93, german: "traf (treffen)", english: "met (to meet) - Präteritum", article: null, category: "Präteritum" },
  { id: 94, german: "dachte (denken)", english: "thought (to think) - Präteritum", article: null, category: "Präteritum" },
  { id: 95, german: "wusste (wissen)", english: "knew (to know) - Präteritum", article: null, category: "Präteritum" },
 
  // Useful nouns
  { id: 96, german: "die Kindheit", english: "childhood", article: "die", category: "Life" },
  { id: 97, german: "der Alltag", english: "daily life / everyday life", article: "der", category: "Life" },
  { id: 98, german: "die Erfahrung", english: "experience", article: "die", category: "Life" },
  { id: 99, german: "die Möglichkeit", english: "opportunity / possibility", article: "die", category: "Life" },
  { id: 100, german: "der Unternehmer", english: "entrepreneur", article: "der", category: "Work" },
  { id: 101, german: "die Lösung", english: "solution", article: "die", category: "Daily Life" },
  { id: 102, german: "der Fahrer", english: "driver", article: "der", category: "People" },
  { id: 103, german: "das Fitnessstudio", english: "gym", article: "das", category: "Daily Life" },
  { id: 104, german: "der Nachbar", english: "neighbour", article: "der", category: "People" },
  { id: 105, german: "die Trophäe", english: "trophy", article: "die", category: "Football" },
  { id: 106, german: "der Erwachsene", english: "adult", article: "der", category: "People" },
  { id: 107, german: "die Verbindung", english: "connection", article: "die", category: "Daily Life" },
  { id: 108, german: "der Zwischenstopp", english: "layover / stopover", article: "der", category: "Travel" },
  { id: 109, german: "die Übernachtung", english: "overnight stay", article: "die", category: "Travel" },
  { id: 110, german: "die Donau", english: "the Danube (river)", article: "die", category: "Places" },
 
  // Useful adjectives & adverbs
  { id: 111, german: "kürzlich", english: "recently", article: null, category: "Adverbs" },
  { id: 112, german: "mindestens", english: "at least", article: null, category: "Adverbs" },
  { id: 113, german: "sofort", english: "immediately", article: null, category: "Adverbs" },
  { id: 114, german: "trotzdem", english: "nevertheless / even so", article: null, category: "Connectors" },
  { id: 115, german: "obwohl", english: "although / even though", article: null, category: "Connectors" },
  { id: 116, german: "weit", english: "far", article: null, category: "Adjectives" },
  { id: 117, german: "vorsichtig", english: "careful", article: null, category: "Adjectives" },
  { id: 118, german: "verantwortungsvoll", english: "responsible", article: null, category: "Adjectives" },
  { id: 119, german: "außergewöhnlich", english: "exceptional / extraordinary", article: null, category: "Adjectives" },
  { id: 120, german: "herzzerreißend", english: "heartbreaking", article: null, category: "Adjectives" },
  { id: 121, german: "sogar", english: "even", article: null, category: "Adverbs" },
  { id: 122, german: "nicht einmal", english: "not even", article: null, category: "Adverbs" },
  { id: 123, german: "wahrscheinlich", english: "probably", article: null, category: "Adverbs" },
  { id: 124, german: "mächtig", english: "powerful", article: null, category: "Adjectives" },
  { id: 125, german: "trocken", english: "dry / boring", article: null, category: "Adjectives" },
  { id: 126, german: "leidenschaftlich", english: "passionate", article: null, category: "Adjectives" },
 
  // Useful verbs
  { id: 127, german: "erreichen", english: "to reach / achieve", article: null, category: "Verbs" },
  { id: 128, german: "übernachten", english: "to stay overnight", article: null, category: "Verbs" },
  { id: 129, german: "abschließen", english: "to complete / finish", article: null, category: "Verbs" },
  { id: 130, german: "aufwachsen", english: "to grow up", article: null, category: "Verbs" },
  { id: 131, german: "teilnehmen", english: "to attend / participate", article: null, category: "Verbs" },
  { id: 132, german: "verarbeiten", english: "to process", article: null, category: "Verbs" },
  { id: 133, german: "sich wiederholen", english: "to repeat", article: null, category: "Verbs" },
  { id: 134, german: "sich kleiden", english: "to dress oneself", article: null, category: "Verbs" },
 
  // Kira's aus/um distinction
  { id: 135, german: "ankommen", english: "to arrive", article: null, category: "Verbs" },
  { id: 136, german: "umkommen", english: "to die / perish (informal: to be overwhelmed)", article: null, category: "Verbs" },
 
  // WM / Sport
  { id: 137, german: "die WM", english: "World Cup (Weltmeisterschaft)", article: "die", category: "Football" },
  { id: 138, german: "der Alarm", english: "alarm", article: "der", category: "Daily Life" },
  { id: 139, german: "überzeugt", english: "convinced", article: null, category: "Adjectives" },
  { id: 140, german: "der Mitarbeiter", english: "employee / worker", article: "der", category: "Work" },
 
  // More reflexive verbs + prepositions (Kira's "Leben im Ausland" list)
  { id: 141, german: "vermissen", english: "to miss (NOT reflexive — ich vermisse dich)", article: null, category: "Verbs" },
  { id: 142, german: "sich verhalten", english: "to behave", article: null, category: "Reflexive Verbs" },
  { id: 143, german: "sich stressen", english: "to stress (oneself) out", article: null, category: "Reflexive Verbs" },
  { id: 144, german: "sich vorstellen", english: "to imagine / introduce oneself (+ bei for professional intro)", article: null, category: "Reflexive Verbs" },
  { id: 145, german: "sich sorgen um", english: "to worry about (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 146, german: "sich treffen mit", english: "to meet with (+ Dat)", article: null, category: "Reflexive Verbs" },
  { id: 147, german: "sich verabschieden von", english: "to say goodbye to (+ Dat)", article: null, category: "Reflexive Verbs" },
  { id: 148, german: "sich ärgern über", english: "to be annoyed about (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 149, german: "sich schämen für", english: "to be ashamed of (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 150, german: "sich wohlfühlen", english: "to feel comfortable / good", article: null, category: "Reflexive Verbs" },
 
  // Life abroad theme (Kira's homework)
  { id: 151, german: "der Umzug", english: "the move (relocation)", article: "der", category: "Life Abroad" },
  { id: 152, german: "umziehen", english: "to move (house/country) - separable, takes sein", article: null, category: "Life Abroad" },
  { id: 153, german: "die Heimat", english: "home / homeland", article: "die", category: "Life Abroad" },
  { id: 154, german: "der Ausländer", english: "foreigner", article: "der", category: "Life Abroad" },
  { id: 155, german: "die Bürokratie", english: "bureaucracy", article: "die", category: "Life Abroad" },
  { id: 156, german: "die Diskriminierung", english: "discrimination", article: "die", category: "Life Abroad" },
  { id: 157, german: "die Lebensqualität", english: "quality of life", article: "die", category: "Life Abroad" },
  { id: 158, german: "die Perspektive", english: "perspective / prospect", article: "die", category: "Life Abroad" },
  { id: 159, german: "unabhängig", english: "independent", article: null, category: "Adjectives" },
  { id: 160, german: "selbstständig", english: "self-reliant / independent", article: null, category: "Adjectives" },
  { id: 161, german: "die Persönlichkeit", english: "personality", article: "die", category: "Life Abroad" },
  { id: 162, german: "die Umgebung", english: "surroundings / environment (local)", article: "die", category: "Daily Life" },
  { id: 163, german: "die Umwelt", english: "environment (nature/ecology)", article: "die", category: "Daily Life" },
 
  // Connectors & small but tricky words
  { id: 164, german: "trotz", english: "despite (+ Genitiv, preposition)", article: null, category: "Connectors" },
  { id: 165, german: "wegen", english: "because of (+ Genitiv, preposition)", article: null, category: "Connectors" },
  { id: 166, german: "während", english: "during (+ Genitiv, preposition)", article: null, category: "Connectors" },
  { id: 167, german: "danach", english: "after that / afterward (time sequence)", article: null, category: "Connectors" },
  { id: 168, german: "deshalb", english: "therefore / that's why (cause-effect)", article: null, category: "Connectors" },
  { id: 169, german: "jeder", english: "everyone / everybody", article: null, category: "Connectors" },
  { id: 170, german: "jemand", english: "someone / somebody", article: null, category: "Connectors" },
  { id: 171, german: "andere", english: "others (Nom/Akk) / anderen (Dat)", article: null, category: "Connectors" },
 
  // Präteritum (irregular verbs, ich-form) — Budapest essay set
  { id: 172, german: "flog (fliegen)", english: "flew (to fly) - Präteritum", article: null, category: "Präteritum" },
  { id: 173, german: "ging (gehen)", english: "went (to go) - Präteritum", article: null, category: "Präteritum" },
  { id: 174, german: "sah (sehen)", english: "saw (to see) - Präteritum", article: null, category: "Präteritum" },
  { id: 175, german: "stand (stehen)", english: "stood (to stand) - Präteritum", article: null, category: "Präteritum" },
  { id: 176, german: "saß (sitzen)", english: "sat (to sit) - Präteritum", article: null, category: "Präteritum" },
  { id: 177, german: "trank (trinken)", english: "drank (to drink) - Präteritum", article: null, category: "Präteritum" },
  { id: 178, german: "aß (essen)", english: "ate (to eat) - Präteritum", article: null, category: "Präteritum" },
  { id: 179, german: "schoss (schießen)", english: "shot (to shoot) - Präteritum", article: null, category: "Präteritum" },
  { id: 180, german: "begann (beginnen)", english: "began (to begin) - Präteritum", article: null, category: "Präteritum" },
  { id: 181, german: "endete (enden)", english: "ended (to end) - Präteritum", article: null, category: "Präteritum" },
  { id: 182, german: "fühlte (fühlen)", english: "felt (to feel) - Präteritum", article: null, category: "Präteritum" },
  { id: 183, german: "sang (singen)", english: "sang (to sing) - Präteritum", article: null, category: "Präteritum" },
  { id: 184, german: "hörte (hören)", english: "heard (to hear) - Präteritum", article: null, category: "Präteritum" },
  { id: 185, german: "freute (freuen)", english: "was happy / looked forward - Präteritum", article: null, category: "Präteritum" },
  { id: 186, german: "lief (laufen)", english: "ran / walked (to run) - Präteritum", article: null, category: "Präteritum" },
  { id: 187, german: "konnte (können)", english: "could (to be able to) - Präteritum", article: null, category: "Präteritum" },
  { id: 188, german: "wollte (wollen)", english: "wanted (to want) - Präteritum", article: null, category: "Präteritum" },
 
  // Relative clauses (Relativsätze) — reference entries
  { id: 189, german: "der / die / das (Relativpronomen Nom)", english: "who / that (subject of relative clause)", article: null, category: "Grammar Reference" },
  { id: 190, german: "den / die / das (Relativpronomen Akk)", english: "whom / that (object of relative clause)", article: null, category: "Grammar Reference" },
  { id: 191, german: "dem / der / dem (Relativpronomen Dat)", english: "to whom / which (after preposition)", article: null, category: "Grammar Reference" },
 
  // Misc from Champions League final + general use
  { id: 192, german: "live", english: "live (e.g. watched live)", article: null, category: "Daily Life" },
  { id: 193, german: "das Stadion", english: "stadium", article: "das", category: "Football" },
  { id: 194, german: "das Tor", english: "goal", article: "das", category: "Football" },
  { id: 195, german: "die Reihe", english: "row", article: "die", category: "Football" },
  { id: 196, german: "produktiv", english: "productive", article: null, category: "Adjectives" },
  { id: 197, german: "der Gedanke", english: "thought (plural: die Gedanken)", article: "der", category: "Daily Life" },
];
 
