const VOCABULARY = [
  // From Kira's lessons - Politics & General
  { id: 1, german: "die Regierung", english: "government", article: "die", category: "Politics" },
  { id: 2, german: "die Demokratie", english: "democracy", article: "die", category: "Politics" },
  { id: 3, german: "das Gesetz", english: "law", article: "das", category: "Politics" },
  { id: 4, german: "die Entscheidung", english: "decision", article: "die", category: "Politics" },
  { id: 5, german: "die Verantwortung", english: "responsibility", article: "die", category: "Politics" },
  { id: 6, german: "die Wahl", english: "election", article: "die", category: "Politics" },
  { id: 7, german: "die Mehrheit", english: "majority", article: "die", category: "Politics" },
  { id: 8, german: "die Opposition", english: "opposition", article: "die", category: "Politics" },
  { id: 9, german: "die Debatte", english: "debate", article: "die", category: "Politics" },
  { id: 10, german: "der Kompromiss", english: "compromise", article: "der", category: "Politics" },

  // From Kira's lessons - Daily Life
  { id: 11, german: "das Medium", english: "medium / means", article: "das", category: "Daily Life" },
  { id: 12, german: "die Mathematik", english: "mathematics", article: "die", category: "Daily Life" },
  { id: 13, german: "die Aktien", english: "stocks / shares", article: "die", category: "Finance", plural: true },
  { id: 14, german: "die Firma", english: "company", article: "die", category: "Work" },
  { id: 15, german: "der Ingenieur", english: "engineer", article: "der", category: "Work" },
  { id: 16, german: "peinlich", english: "embarrassing", article: null, category: "Adjectives" },
  { id: 17, german: "verständlich", english: "understandable", article: null, category: "Adjectives" },
  { id: 18, german: "verwirrend", english: "confusing", article: null, category: "Adjectives" },
  { id: 19, german: "darum", english: "that's why / therefore", article: null, category: "Connectors" },
  { id: 20, german: "das Ticket", english: "ticket", article: "das", category: "Travel" },

  // Football / Budapest
  { id: 21, german: "der Sieg", english: "victory", article: "der", category: "Football" },
  { id: 22, german: "unentschieden", english: "draw", article: null, category: "Football" },
  { id: 23, german: "der Außenseiter", english: "underdog", article: "der", category: "Football" },
  { id: 24, german: "das Elfmeterschießen", english: "penalty shootout", article: "das", category: "Football" },
  { id: 25, german: "die Niederlage", english: "defeat", article: "die", category: "Football" },
  { id: 26, german: "die Atmosphäre", english: "atmosphere", article: "die", category: "Football" },
  { id: 27, german: "die Gänsehaut", english: "goosebumps", article: "die", category: "Feelings" },
  { id: 28, german: "leidenschaftlich", english: "passionate", article: null, category: "Adjectives" },
  { id: 29, german: "einzigartig", english: "unique", article: null, category: "Adjectives" },
  { id: 30, german: "unvergesslich", english: "unforgettable", article: null, category: "Adjectives" },
  { id: 31, german: "überzeugt", english: "convinced", article: null, category: "Adjectives" },

  // Travel
  { id: 32, german: "der Zwischenstopp", english: "layover", article: "der", category: "Travel" },
  { id: 33, german: "die Rückreise", english: "return journey", article: "die", category: "Travel" },
  { id: 34, german: "das Terminal", english: "terminal", article: "das", category: "Travel" },
  { id: 35, german: "das Geschäft", english: "shop", article: "das", category: "Daily Life" },
  { id: 36, german: "angekommen", english: "arrived", article: null, category: "Travel" },

  // People / Social
  { id: 37, german: "der Kellner", english: "waiter", article: "der", category: "People" },
  { id: 38, german: "der Mitarbeiter", english: "worker / employee", article: "der", category: "Work" },
  { id: 39, german: "die Bekannten", english: "acquaintances", article: "die", category: "People", plural: true },

  // TV / Film
  { id: 40, german: "der Untertitel", english: "subtitle", article: "der", category: "Film & TV" },
  { id: 41, german: "die Episode / die Folge", english: "episode", article: "die", category: "Film & TV" },
  { id: 42, german: "die Serie", english: "TV show / series", article: "die", category: "Film & TV" },
  { id: 43, german: "die Staffel", english: "season (of a show)", article: "die", category: "Film & TV" },
  { id: 44, german: "die Leiche", english: "body (dead)", article: "die", category: "Film & TV" },
  { id: 45, german: "der Mord", english: "murder", article: "der", category: "Film & TV" },
  { id: 46, german: "die Lawine", english: "avalanche", article: "die", category: "Nature" },
  { id: 47, german: "die Brücke", english: "bridge", article: "die", category: "Places" },

  // Language learning
  { id: 48, german: "das Hörverständnis", english: "listening comprehension", article: "das", category: "Language" },
  { id: 49, german: "die Dauer", english: "duration", article: "die", category: "Language" },
  { id: 50, german: "die Geschwindigkeit", english: "speed", article: "die", category: "Language" },
  { id: 51, german: "das Muster", english: "pattern", article: "das", category: "Language" },
  { id: 52, german: "das Abo", english: "subscription", article: "das", category: "Daily Life" },
  { id: 53, german: "selten", english: "rarely", article: null, category: "Adverbs" },
  { id: 54, german: "einige", english: "quite a few / some", article: null, category: "Adverbs" },
  { id: 55, german: "außer", english: "except", article: null, category: "Connectors" },
  { id: 56, german: "unglaublich", english: "incredible / unbelievable", article: null, category: "Adjectives" },
  { id: 57, german: "der Satz", english: "sentence / phrase", article: "der", category: "Language" },

  // Feelings
  { id: 58, german: "aufgeregt", english: "excited (positive)", article: null, category: "Feelings" },
  { id: 59, german: "enttäuscht", english: "disappointed", article: null, category: "Feelings" },
  { id: 60, german: "zufrieden", english: "satisfied", article: null, category: "Feelings" },
  { id: 61, german: "einsam", english: "lonely", article: null, category: "Feelings" },
  { id: 62, german: "beschäftigt", english: "busy", article: null, category: "Adjectives" },
  { id: 63, german: "herzzerreißend", english: "heartbreaking", article: null, category: "Feelings" },

  // Reflexive verbs
  { id: 64, german: "sich erinnern an", english: "to remember (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 65, german: "sich freuen auf", english: "to look forward to (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 66, german: "sich freuen über", english: "to be happy about (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 67, german: "sich beschweren über", english: "to complain about (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 68, german: "sich kümmern um", english: "to take care of (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 69, german: "sich gewöhnen an", english: "to get used to (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 70, german: "sich anpassen an", english: "to adapt to (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 71, german: "sich interessieren für", english: "to be interested in (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 72, german: "sich entscheiden für", english: "to decide on (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 73, german: "sich vorbereiten auf", english: "to prepare for (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 74, german: "sich konzentrieren auf", english: "to focus on (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 75, german: "sich beschäftigen mit", english: "to deal with (+ Dat)", article: null, category: "Reflexive Verbs" },
  { id: 76, german: "sich einigen auf", english: "to agree on (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 77, german: "sich bemühen um", english: "to make an effort (+ Akk)", article: null, category: "Reflexive Verbs" },
  { id: 78, german: "sich verändern", english: "to change (oneself)", article: null, category: "Reflexive Verbs" },
  { id: 79, german: "sich entwickeln", english: "to develop", article: null, category: "Reflexive Verbs" },
  { id: 80, german: "sich fühlen", english: "to feel", article: null, category: "Reflexive Verbs" },
  { id: 81, german: "sich entspannen", english: "to relax", article: null, category: "Reflexive Verbs" },
  { id: 82, german: "sich verbessern", english: "to improve oneself", article: null, category: "Reflexive Verbs" },

  // Präteritum forms
  { id: 83, german: "war (sein)", english: "was (to be) - Präteritum", article: null, category: "Präteritum" },
  { id: 84, german: "hatte (haben)", english: "had (to have) - Präteritum", article: null, category: "Präteritum" },
  { id: 85, german: "ging (gehen)", english: "went (to go) - Präteritum", article: null, category: "Präteritum" },
  { id: 86, german: "kam (kommen)", english: "came (to come) - Präteritum", article: null, category: "Präteritum" },
  { id: 87, german: "flog (fliegen)", english: "flew (to fly) - Präteritum", article: null, category: "Präteritum" },
  { id: 88, german: "sah (sehen)", english: "saw (to see) - Präteritum", article: null, category: "Präteritum" },
  { id: 89, german: "trank (trinken)", english: "drank (to drink) - Präteritum", article: null, category: "Präteritum" },
  { id: 90, german: "sang (singen)", english: "sang (to sing) - Präteritum", article: null, category: "Präteritum" },
  { id: 91, german: "gewann (gewinnen)", english: "won (to win) - Präteritum", article: null, category: "Präteritum" },
  { id: 92, german: "verlor (verlieren)", english: "lost (to lose) - Präteritum", article: null, category: "Präteritum" },
  { id: 93, german: "traf (treffen)", english: "met (to meet) - Präteritum", article: null, category: "Präteritum" },
  { id: 94, german: "dachte (denken)", english: "thought (to think) - Präteritum", article: null, category: "Präteritum" },
  { id: 95, german: "wusste (wissen)", english: "knew (to know) - Präteritum", article: null, category: "Präteritum" },

  // Useful nouns
  { id: 96, german: "die Kindheit", english: "childhood", article: "die", category: "Life" },
  { id: 97, german: "der Alltag", english: "daily life / everyday life", article: "der", category: "Life" },
  { id: 98, german: "die Erfahrung", english: "experience", article: "die", category: "Life" },
  { id: 99, german: "die Möglichkeit", english: "opportunity / possibility", article: "die", category: "Life" },
  { id: 100, german: "der Unternehmer", english: "entrepreneur", article: "der", category: "Work" },
  { id: 101, german: "die Lösung", english: "solution", article: "die", category: "Daily Life" },
  { id: 102, german: "der Fahrer", english: "driver", article: "der", category: "People" },
  { id: 103, german: "das Fitnessstudio", english: "gym", article: "das", category: "Daily Life" },
  { id: 104, german: "der Nachbar", english: "neighbour", article: "der", category: "People" },
  { id: 105, german: "die Trophäe", english: "trophy", article: "die", category: "Football" },
  { id: 106, german: "der Erwachsene", english: "adult", article: "der", category: "People" },
  { id: 107, german: "die Verbindung", english: "connection", article: "die", category: "Daily Life" },
  { id: 108, german: "der Zwischenstopp", english: "layover / stopover", article: "der", category: "Travel" },
  { id: 109, german: "die Übernachtung", english: "overnight stay", article: "die", category: "Travel" },
  { id: 110, german: "die Donau", english: "the Danube (river)", article: "die", category: "Places" },

  // Useful adjectives & adverbs
  { id: 111, german: "kürzlich", english: "recently", article: null, category: "Adverbs" },
  { id: 112, german: "mindestens", english: "at least", article: null, category: "Adverbs" },
  { id: 113, german: "sofort", english: "immediately", article: null, category: "Adverbs" },
  { id: 114, german: "trotzdem", english: "nevertheless / even so", article: null, category: "Connectors" },
  { id: 115, german: "obwohl", english: "although / even though", article: null, category: "Connectors" },
  { id: 116, german: "weit", english: "far", article: null, category: "Adjectives" },
  { id: 117, german: "vorsichtig", english: "careful", article: null, category: "Adjectives" },
  { id: 118, german: "verantwortungsvoll", english: "responsible", article: null, category: "Adjectives" },
  { id: 119, german: "außergewöhnlich", english: "exceptional / extraordinary", article: null, category: "Adjectives" },
  { id: 120, german: "herzzerreißend", english: "heartbreaking", article: null, category: "Adjectives" },
  { id: 121, german: "sogar", english: "even", article: null, category: "Adverbs" },
  { id: 122, german: "nicht einmal", english: "not even", article: null, category: "Adverbs" },
  { id: 123, german: "wahrscheinlich", english: "probably", article: null, category: "Adverbs" },
  { id: 124, german: "mächtig", english: "powerful", article: null, category: "Adjectives" },
  { id: 125, german: "trocken", english: "dry / boring", article: null, category: "Adjectives" },
  { id: 126, german: "leidenschaftlich", english: "passionate", article: null, category: "Adjectives" },

  // Useful verbs
  { id: 127, german: "erreichen", english: "to reach / achieve", article: null, category: "Verbs" },
  { id: 128, german: "übernachten", english: "to stay overnight", article: null, category: "Verbs" },
  { id: 129, german: "abschließen", english: "to complete / finish", article: null, category: "Verbs" },
  { id: 130, german: "aufwachsen", english: "to grow up", article: null, category: "Verbs" },
  { id: 131, german: "teilnehmen", english: "to attend / participate", article: null, category: "Verbs" },
  { id: 132, german: "verarbeiten", english: "to process", article: null, category: "Verbs" },
  { id: 133, german: "sich wiederholen", english: "to repeat", article: null, category: "Verbs" },
  { id: 134, german: "sich kleiden", english: "to dress oneself", article: null, category: "Verbs" },

  // Kira's aus/um distinction
  { id: 135, german: "ankommen", english: "to arrive", article: null, category: "Verbs" },
  { id: 136, german: "umkommen", english: "to die / perish (informal: to be overwhelmed)", article: null, category: "Verbs" },

  // WM / Sport
  { id: 137, german: "die WM", english: "World Cup (Weltmeisterschaft)", article: "die", category: "Football" },
  { id: 138, german: "der Alarm", english: "alarm", article: "der", category: "Daily Life" },
  { id: 139, german: "überzeugt", english: "convinced", article: null, category: "Adjectives" },
  { id: 140, german: "der Mitarbeiter", english: "employee / worker", article: "der", category: "Work" },
];
